"""DiagnosticPlan Framework (Phase 5).

Declarative plan definitions compile to a version-pinned ``PlanIR`` and run on a
deterministic executor with 9 typed step handlers.  No arbitrary recursion,
eval/exec, SQL, prompt or LLM.
"""

from app.commerce.diagnostics.plans.compiler import CompileContext, PlanCompiler
from app.commerce.diagnostics.plans.executor import (
    PlanContext,
    PlanExecutionError,
    PlanExecutor,
)
from app.commerce.diagnostics.plans.ir import (
    CompiledStep,
    PinnedRef,
    PlanIR,
    REF_KINDS,
    REF_METRIC,
    REF_POLICY,
    REF_RULE_SET,
    REF_IMPACT_FORMULA,
    REF_PRIORITY_POLICY,
)
from app.commerce.diagnostics.plans.parser import parse_plan
from app.commerce.diagnostics.plans.period import resolve_period
from app.commerce.diagnostics.plans.ports import (
    FACT_QUALITY_INSUFFICIENT,
    FACT_QUALITY_PARTIAL,
    FACT_QUALITY_VALID,
    FRESHNESS_FRESH,
    FRESHNESS_STALE,
    FRESHNESS_UNKNOWN,
    FactQueryExecutorPort,
    FactQueryResult,
    FactQuerySpec,
    FakeFactQueryExecutor,
    TrustedExecutionContext,
)
from app.commerce.diagnostics.plans.registry import DiagnosticPlanRegistry
from app.commerce.diagnostics.plans.schema import (
    FAILURE_MARK_UNKNOWN,
    FAILURE_POLICIES,
    FAILURE_SKIP,
    FAILURE_STOP,
    PLAN_ACTIVE,
    PLAN_DEPRECATED,
    PLAN_DISABLED,
    PLAN_DRAFT,
    PLAN_STATUSES,
    PLAN_VALIDATED,
    STEP_ANOMALY_DETECT,
    STEP_CONTRIBUTION_ANALYZE,
    STEP_DATA_QUALITY_GATE,
    STEP_FACT_QUERY,
    STEP_IMPACT_ESTIMATE,
    STEP_METRIC_COMPUTE,
    STEP_PRIORITY_EVALUATE,
    STEP_RESULT_ASSEMBLE,
    STEP_RULE_EVALUATE,
    STEP_STATUS_FAILED,
    STEP_STATUS_MARKED_UNKNOWN,
    STEP_STATUS_PENDING,
    STEP_STATUS_SKIPPED,
    STEP_STATUS_SUCCEEDED,
    STEP_TYPES,
    STOP_INSUFFICIENT_DATA,
    STOP_NORMAL,
    STOP_OUTCOMES,
    STOP_SUCCESS,
    STOP_UNSUPPORTED,
    PlanDefinition,
    StepDefinition,
    WhenCondition,
    DataQualityRequirement,
)
from app.commerce.diagnostics.plans.state import PlanExecutionState, StepTrace
from app.commerce.diagnostics.plans.validator import (
    MaxDepthExceededError,
    PlanValidationError,
    SecurityFieldViolation,
    validate_plan,
)
from app.commerce.diagnostics.plans.when import (
    WHEN_EQ,
    WHEN_EXISTS,
    WHEN_GT,
    WHEN_GTE,
    WHEN_IN,
    WHEN_LT,
    WHEN_LTE,
    WHEN_NOT_EXISTS,
    WHEN_OPERATORS,
)

__all__ = [
    "PlanDefinition",
    "StepDefinition",
    "WhenCondition",
    "DataQualityRequirement",
    "PlanIR",
    "PinnedRef",
    "CompiledStep",
    "PlanCompiler",
    "CompileContext",
    "PlanExecutor",
    "PlanContext",
    "PlanExecutionError",
    "PlanExecutionState",
    "StepTrace",
    "DiagnosticPlanRegistry",
    "parse_plan",
    "validate_plan",
    "PlanValidationError",
    "MaxDepthExceededError",
    "SecurityFieldViolation",
    "resolve_period",
    "FactQueryExecutorPort",
    "FactQuerySpec",
    "FactQueryResult",
    "FakeFactQueryExecutor",
    "TrustedExecutionContext",
    "FACT_QUALITY_VALID",
    "FACT_QUALITY_PARTIAL",
    "FACT_QUALITY_INSUFFICIENT",
    "FRESHNESS_FRESH",
    "FRESHNESS_STALE",
    "FRESHNESS_UNKNOWN",
    "REF_KINDS",
    "REF_METRIC",
    "REF_POLICY",
    "REF_RULE_SET",
    "REF_IMPACT_FORMULA",
    "REF_PRIORITY_POLICY",
    "STEP_TYPES",
    "STEP_FACT_QUERY",
    "STEP_METRIC_COMPUTE",
    "STEP_DATA_QUALITY_GATE",
    "STEP_ANOMALY_DETECT",
    "STEP_CONTRIBUTION_ANALYZE",
    "STEP_RULE_EVALUATE",
    "STEP_IMPACT_ESTIMATE",
    "STEP_PRIORITY_EVALUATE",
    "STEP_RESULT_ASSEMBLE",
    "STOP_OUTCOMES",
    "STOP_SUCCESS",
    "STOP_NORMAL",
    "STOP_INSUFFICIENT_DATA",
    "STOP_UNSUPPORTED",
    "FAILURE_POLICIES",
    "FAILURE_SKIP",
    "FAILURE_MARK_UNKNOWN",
    "FAILURE_STOP",
    "PLAN_STATUSES",
    "PLAN_DRAFT",
    "PLAN_VALIDATED",
    "PLAN_ACTIVE",
    "PLAN_DEPRECATED",
    "PLAN_DISABLED",
    "STEP_STATUS_PENDING",
    "STEP_STATUS_SUCCEEDED",
    "STEP_STATUS_SKIPPED",
    "STEP_STATUS_FAILED",
    "STEP_STATUS_MARKED_UNKNOWN",
    "WHEN_OPERATORS",
    "WHEN_EQ",
    "WHEN_IN",
    "WHEN_GT",
    "WHEN_GTE",
    "WHEN_LT",
    "WHEN_LTE",
    "WHEN_EXISTS",
    "WHEN_NOT_EXISTS",
]
